version: "3.8"
services:
  web:
    build:
      context: .
      args:
        - POSTGRES_HOST=postgres
    container_name: my-app
    ports:
      - "3000:3000"
  postgres:
    container_name: postgres
    image: "postgres"
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
volumes:
  postgres:
