version: "3.8"
services:
  web:
    build: .
    container_name: my-app
    ports:
      - "3000:3000"
    links:
      - postgres
  postgres:
    container_name: db-container
    image: "postgres"
    restart: always
    environment:
      POSTGRES_DB: fcl-postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5440:5432"
volumes:
  postgres:
